version: "2"
output:
  formats:
    tab:
      path: stdout
    junit-xml:
      path: report.xml
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - ginkgolinter
    - gomodguard
    - revive
    - sloglint
    - spancheck
    - sqlclosecheck
    - thelper
    - varnamelen

    # TMP
    - cyclop
    - funlen
    - godox
    - wrapcheck

    # Deprecated
    - wsl

  settings:
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake

formatters:
  enable:
    - gofmt
    - goimports
    - golines
